### DISCUSSION TITLE
alternatives for mailhog and minio docker images.

### DISCUSSION THREAD

**Discussion by xmlking** [nhost/nhost#2702] [Ideas]
Proposing alternative docker images for `mailhog` and `minio` for local development with `nhost up` for better developer experience.  

1. `minio/minio` don't have option to auto create `MINIO_DEFAULT_BUCKETS` but [bitnami/minio](https://github.com/bitnami/containers/blob/main/bitnami/minio/README.md) docker image has those additional options, You can create a series of buckets in the MinIO server during the initialization of the container by setting the environment variable MINIO_DEFAULT_BUCKETS as shown below (policy is optional). healthcheck are bonus 
2.  `axllent/mailpit` is better alternative for `mailhog` which provide more control and healthchecks. `mailhog` is not maintained for over 2 years.  
```yaml
services:
  ###########################################################################
  # mailpit - instead of mailhog
  ###########################################################################
  mailpit:
    image: axllent/mailpit:v1.16.0
    hostname: mailpit
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH: 'user:password'
      # MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 'true'
      TZ: ${CONTAINER_TIMEZONE:-America/Los_Angeles}
    expose:
      - 1025 # MP_SMTP_BIND_ADDR
      - 8025 # MP_UI_BIND_ADDR
    volumes:
      - mailhog:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:8025/livez"] # for k8 /readyz
      interval: 60s
      start_period: 1m
      start_interval: 10s
      timeout: 15s
      retries: 5
  ###########################################################################
  # minio
  ###########################################################################
  minio:
    image: bitnami/minio:2024.4.6
    hostname: minio
    container_name: minio
    restart: unless-stopped
    volumes:
      - minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-apps:download,public:public}
    expose:
      - 9000
      - 9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 60s
      start_period: 1m
      start_interval: 10s
      timeout: 15s
      retries: 5
```
