### DISCUSSION TITLE
How do i update environment variables from NHost Functions ?

### DISCUSSION THREAD

**Discussion by vsundar17697** [nhost/nhost#2754] [Q&A] [answered]
Hi, I use firebase auth for my application and pretty much looking to use the rest of the suite from NHost. 

I'm unable to setup NHost Hasura to verify firebase jwt because of toml rules that are present from nhost side. 

The only way i get this to work is to manually get the appropriate kid from 
`https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com`
and set the value as a `HASURA_GRAPHQL_JWT_SECRET`

This is **pain**. 
While you guys fix this, i thought i could at least have this updated using an NHost function that runs daily once or something. However i struggle to find documentation to update the environment variable. 

Could you please help with this.

**Comment by dbarrosop** [comment, marked as answer]
> I'm unable to setup NHost Hasura to verify firebase jwt because of toml rules that are present from nhost side.

What issue are you having? Using something like jwk_url should work. For instance:

```toml
[[hasura.jwtSecrets]]
jwk_url = 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com'
```

or whatever other URL to fetch the JWK you may need.
