### DISCUSSION TITLE
Creating a custom token for row access control

### DISCUSSION THREAD

**Discussion by Subh94** [nhost/nhost#2863] [Q&A] [answered]
I created a auth.session.accessToken.customClaims and provide a valid path like
key = 'Vendor-Id'
value = 'org.organization_id'

Where graphQL Query can resolve value on defined user and organization member but X-Hasura-Vendor-Id is not reflecting on graphql and throwing an error

{
"errors": [
{
"message": "missing session variable: "x-hasura-vendor-id"",
"extensions": {
"path": "$",
"code": "not-found"
}
}
]
}

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/a98ab6ce-ae2b-4df3-94a3-e560021b0195">
Created a Permission Variable as above described on nhost https://docs.nhost.io/guides/api/permissions#permission-variables

Anything I am missing

**Comment by dbarrosop** [comment]
Hello,
have you tried decoding the access token to check the claims? Is there anything on the logs? If there is an issue with the custom claim it might show up in there.

Regards

**Reply by Subh94** [reply]
```
{
  "errors": [
    {
      "message": "missing session variable: \"x-hasura-vendor-id\"",
      "extensions": {
        "path": "$",
        "code": "not-found"
      }
    }
  ]
}

```

I am getting above error while 

```
{
  "exp": 1725549281,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "Vendor Admin"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "4db64f42-2624-4394-b6be-fecb24498954",
    "x-hasura-user-is-anonymous": "false",
    "x-hasura-vendor-id": "0a903fc0-2e35-443b-89dd-3934d2e4e94c"
  },
  "iat": 1725548381,
  "iss": "hasura-auth",
  "sub": "4db64f42-2624-4394-b6be-fecb24498954"
}
```

Have `x-hasura-vendor-id` available.

**Reply by dbarrosop** [reply]
Ok, the issue doesn't seem to be in the auth service then. Could you provide more details about your graphql configuration (metadata, permissions, whatever is relevant here) and the graphql query triggering this issue?

**Reply by Subh94** [reply]
I didn't made any changes apart from what nhost provides 

```
Current Server Version:
v2.38.0-ce
Console asset version:
1711897898491

Hasura settings 
[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']
liveQueriesMultiplexedRefetchInterval = 1000
stringifyNumericTypes = false
```

Here is my table yaml 
```
table:
  name: organization_members
  schema: public
object_relationships:
  - name: organization
    using:
      foreign_key_constraint_on: organization_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: Guest Receptionist
    permission:
      columns:
        - organization_member_id
        - organization_id
        - user_id
        - role
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      allow_aggregations: true
  - role: Vendor Admin
    permission:
      columns:
        - organization_member_id
        - organization_id
        - user_id
        - role
        - created_at
        - updated_at
        - created_by
        - latest_updated_by
      filter:
        _or:
          - user_id:
              _eq: X-Hasura-User-Id
          - organization_id:
              _eq: x-hasura-vendor-id
      allow_aggregations: true
```

```graphql
{
    organization_members{
      organization_id
      user_id
    }
}

```

Response 
```
{
  "errors": [
    {
      "message": "missing session variable: \"x-hasura-vendor-id\"",
      "extensions": {
        "path": "$",
        "code": "not-found"
      }
    }
  ]
}
```

I have tried GraphQL option on nhost dashboard to enforce user 
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/d04c12ec-bcb6-4edf-83d2-5530af60d27c">


Please let me know any additional details needed or direction I should seek.
