### ISSUE TITLE
Suggestion: Webhook workflow for OTP authentication

### ISSUE THREAD

**Issue by israelidanny** [nhost/nhost#1896]
**Is your feature request related to a problem? Please describe.**
Right now only Twilio is supported. This is subpar because in some countries there is poor support for Twilio, as well as pricing concerns for some situations. 

**Describe the solution you'd like**
Ideally there would be a "webhook" provider for OTP authentication. It would send a webhook to any custom address with the payload specifying the phone, e.t.c

**Describe alternatives you've considered**
An alternative would be manually adding any provider that's large enough, but such an approach isn't customizeable enough and adds too much maintenance overhead.

**Additional context**
Supabase are working on a very similar approach exactly because of the above concern.

P.S
I am more than willing to contribute some code in a PR to help make this happen if the general idea is acceptable.

**Comment by dbarrosop** [comment]
> Ideally there would be a "webhook" provider for OTP authentication

This seems like a reasonable approach. I think we mostly need to agree on how this would look like.

Do you have any suggestion on how the workflow would look like and what the request/response would look like?

/cc @nunopato

**Comment by israelidanny** [comment]
So for `config.yaml` I would envision something like this:
```yaml
  sms:
    enabled: true
    passwordless:
      enabled: true
    provider:
      twilio:
        account_sid: ""
        auth_token: ""
        from: ""
        messaging_service_id: ""
        enabled: false
      webhook:
        url: "http://some.address/webhook"
        # could be any key but is recommended to be at least 256 bit (https://www.rfc-editor.org/rfc/rfc2104#section-3)
        hmac_secret: "RfUjXn2r5u8x/A?D(G+KbPeShVkYp3s6"
        enabled: true
```

From the SDK client you still do simple calls like this:
```javascript
// Step 1: Send OTP to the user's phone number
await nhost.auth.signIn({
  phoneNumber: '+11233213123'
})

// Step 2: Sign in user using their phone number and OTP
await nhost.auth.signIn({
  phoneNumber: '+11233213123'
  otp: '123456',
})
```

On the webhook side, you would get a POST request with JSON body, presumably containing something like this as a payload:
```json
{
  "userId": "97cd32c0-60e2-4796-a271-f034661f36fe",
  "phoneNumber": "+11233213123",
  "otp": "123456"
}
```

The headers would include this:
```http
X-Timestamp: 1683209337
X-Content-SHA256: 0bdaef46f4d03f40fe15f898485c0942dee9d3e5c2d0d5e54b729e7bbe49079d
Authorization: HMAC-SHA256 Credential=sms&SignedHeaders=x-timestamp;host;x-content-sha256&Signature={Signature}
```

`X-Content-SHA256` is a pre-computed SHA256 of the request content, and `X-Timestamp` helps us prevent replay attacks. `Credential` can be anything static really (since we're not really introducing dynamic credential storage), and `{Signature}` is something like:
`BASE64(HMACSHA256(HTTP_METHOD + '\n' + path_and_query + '\n' + signed_headers_values, Secret))`

All of this can be easily simplified by adding a `verifySignature` method to the JS client SDK.

**Nuances:**

- Delivery guarantee: Should be out of scope for this task. If nhost already has some retry mechanism for Twilio, we re-use that. If not, it's a story for a different PR.

**Prior Art:**

- https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-hmac
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html
- https://docs.oracle.com/en/cloud/saas/marketing/crowdtwist-develop/Developers/HMACAuthentication.html
- https://stripe.com/docs/webhooks/signatures
