### ISSUE TITLE
Self Hosting from Docker-Compose: 404s, bad route mappings

### ISSUE THREAD

**Issue by komali2** [nhost/nhost#2522]
**Describe the bug**

**To Reproduce**
1. Follow the instructions of the docker compose readme: https://github.com/nhost/nhost/tree/main/examples/docker-compose
2. Do the following, per instructions:
```
git clone https://github.com/nhost/nhost
cd nhost/examples/docker-compose
cp .env.example .env
docker-compose up -d
```
3. Edit the `.env` with real values:

```
POSTGRES_PASSWORD={a postgres secret}
HASURA_GRAPHQL_ADMIN_SECRET={a graphql admin secret}
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256", "key":"{this i left as the default secret because i was confused}","issuer":"hasura-auth"}'
STORAGE_ACCESS_KEY={a storage access key secret}
STORAGE_SECRET_KEY={a storage secret secret}
```
5. Start the containers. 
```
docker compose up -d
```

6. Observe seemingly healthy and happy containers with `docker ps`

```
CONTAINER ID   IMAGE                                      COMMAND                   CREATED         STATUS                   PORTS                                                                                          NAMES
d5d902fb835a   nhost/hasura-storage:0.3.1                 "/nix/store/2h36i65d…"    8 minutes ago   Up 7 minutes             8000/tcp                                                                                       docker-compose-storage-1
8cbf9d68f1cd   nhost/hasura-auth:0.16.2                   "docker-entrypoint.s…"    8 minutes ago   Up 8 minutes (healthy)   4000/tcp                                                                                       docker-compose-auth-1
dd537a1af231   hasura/graphql-engine:v2.15.2              "/bin/sh -c '\"${HGE_…"   8 minutes ago   Up 8 minutes             8080/tcp                                                                                       docker-compose-graphql-engine-1
3667ac39011c   postgres                                   "docker-entrypoint.s…"    8 minutes ago   Up 8 minutes             0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                      docker-compose-postgres-1
59c987931c2e   traefik:v2.5                               "/entrypoint.sh --ap…"    8 minutes ago   Up 8 minutes             80/tcp, 0.0.0.0:1337->1337/tcp, :::1337->1337/tcp, 0.0.0.0:9090->8080/tcp, :::9090->8080/tcp   traefik
756fe2091a79   minio/minio:RELEASE.2021-09-24T00-24-24Z   "sh -c 'mkdir -p /da…"    8 minutes ago   Up 8 minutes             0.0.0.0:8484->8484/tcp, :::8484->8484/tcp, 9000/tcp                                            docker-compose-minio-1
967d124198c7   nhost/dashboard:0.7.4                      "./docker-entrypoint…"    8 minutes ago   Up 8 minutes             0.0.0.0:3030->3000/tcp, :::3030->3000/tcp                                                      docker-compose-dashboard-1
27ce75bae2ee   mailhog/mailhog                            "MailHog"                 8 minutes ago   Up 8 minutes             0.0.0.0:1025->1025/tcp, :::1025->1025/tcp, 0.0.0.0:8025->8025/tcp, :::8025->8025/tcp           docker-compose-mailhog-1
c8a170af7f2d   nhost/functions:0.1.8                      "docker-entrypoint.s…"    8 minutes ago   Up 8 minutes             3000/tcp                                                                                       docker-compose-functions-1

```
7. Per (slightly confusing) instructions, install and run hasura console on the host machine (outside the containers)
```
hasura console
```
8. Route ports to the service of your choice, either via reverse proxy, cloudflare tunnels, etc
9. Try pinging any of the above services, find only errors, for everything other than mailhog and traefik. For example, trying a URL routed to `localhost:1337` should show the Hasura Console. Instead, it 404:

![2024-02-08-114845_1222x543_scrot](https://github.com/nhost/nhost/assets/8533113/0940c108-b501-49f9-94c4-c1eeb4287868)

Try the nhost dashboard, at localhost:3030. A page loads, but shows "error connecting" :

![2024-02-08-115011_1224x572_scrot](https://github.com/nhost/nhost/assets/8533113/24f63c58-994c-451e-86ea-a9bbabc1844d)

Odd. Well, the `hasura console` command output a route at `localhost:9695` so route to that and try hitting it. Get a login window for which none of the secrets in the env file resolve, because requests seem to be routing to `localhost` instead of a published URL.:

![2024-02-08-115148_1237x613_scrot](https://github.com/nhost/nhost/assets/8533113/499aa96e-3acf-423a-8a27-3a7fc0e06f48)

**Expected behavior**
Per instructions, expect to be able to self-host nhost stack. 

Poking around the issues on github, I'm guessing there's some more environment variables that need to be tweaked. I'm more than happy to issue PRs updating documentation to make the process very explicit for self hosting, as I find this stack as advertised to be absolutely perfect for my co-op's needs and would love to make it easy for others to use as well. To do so, I just need a little guidance on what I'm doing wrong here. Should I be adding some more environment variables to the env file? Tweaking the docker compose? (I saw a closed PR where it was tweaked)

**Desktop (please complete the following information):**
 - OS: Host machine: Ubuntu 18.04.6 LTS
 - OS: Client machine: Manjaro 23.1.3
 - Browser Client: Brave
 - Version [e.g. 22]: Please see docker-compose, below

**Additional context**

`docker-compose.yml` from example:

```
version: '3.6'
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1337"
    ports:
      - "1337:1337"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.15.2
    depends_on:
      - 'postgres'
    restart: always
    expose:
      - 8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.hasura.entrypoints=web"
  auth:
    image: nhost/hasura-auth:0.16.2
    depends_on:
      - postgres
      - graphql-engine
    restart: always
    volumes:
      - ./emails:/app/email-templates
    environment:
      AUTH_HOST: '0.0.0.0'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      AUTH_CLIENT_URL: ${AUTH_CLIENT_URL:-http://localhost:3000}
      AUTH_SMTP_HOST: mailhog
      AUTH_SMTP_PORT: 1025
      AUTH_SMTP_USER: user
      AUTH_SMTP_PASS: password
      AUTH_SMTP_SENDER: mail@example.com
    expose: 
      - 4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=/v1/auth"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/v1/auth`)"
      - "traefik.http.routers.auth.middlewares=strip-auth@docker"
      - "traefik.http.routers.auth.entrypoints=web"
  storage:
    image: nhost/hasura-storage:0.3.1
    depends_on:
      - postgres
      - graphql-engine
      - minio
    restart: always
    expose:
      - 8000
    environment:
      PUBLIC_URL: http://localhost:${PROXY_PORT:-1337}
      HASURA_METADATA: 1
      HASURA_ENDPOINT: http://graphql-engine:8080/v1
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      S3_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      S3_SECRET_KEY: ${STORAGE_SECRET_KEY}
      S3_ENDPOINT: http://minio:8484
      S3_BUCKET: nhost
      POSTGRES_MIGRATIONS: 1
      POSTGRES_MIGRATIONS_SOURCE: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres?sslmode=disable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage.rule=Host(`localhost`) && PathPrefix(`/v1/storage`)"
      - "traefik.http.routers.storage.entrypoints=web"
      # Rewrite the path so it matches with the new storage API path introduced in hasura-s...skipping...
      - 3000
    volumes:
      - .:/opt/project
      - functions_node_modules:/opt/project/node_modules
      - /opt/project/data/
      - /opt/project/initdb.d/
  minio:
    image: minio/minio:RELEASE.2021-09-24T00-24-24Z
    entrypoint: sh
    command: -c 'mkdir -p /data/nhost && /opt/bin/minio server --address :8484 /data'
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    ports:
      - ${MINIO_PORT:-8484}:8484
    volumes:
      - ./data/minio:/data
  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      SMTP_USER: ${AUTH_SMTP_USER:-user}
      SMTP_SECURE: "${AUTH_SMTP_SECURE:-false}"
      SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    ports:
      - ${AUTH_SMTP_PORT:-1025}:1025 
      - 8025:8025
    volumes:
      - ./data/mailhog:/maildir
  dashboard:
    image: nhost/dashboard:0.7.4
    ports:
      - "3030:3000"
volumes:
  functions_node_modules:

```

`.env` file:

```
POSTGRES_PASSWORD={a postgres secret}
HASURA_GRAPHQL_ADMIN_SECRET={a graphql admin secret}
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256", "key":"{this i left as the default secret because i was confused}","issuer":"hasura-auth"}'
STORAGE_ACCESS_KEY={a storage access key secret}
STORAGE_SECRET_KEY={a storage secret secret}
```
