### ISSUE TITLE
Infinite Loop in Client-Side Token Refresh When Refresh Token is Deleted from Database

### ISSUE THREAD

**Issue by jovermier** [nhost/nhost#2763]
**Describe the bug**
When the refresh token is deleted from the database, the client side enters an infinite loop attempting to refresh the token. This results in hundreds of network requests to the authentication service happening per second.

**To Reproduce**
1. Go to the application.
2. Log into the application as a user.
3. Delete the refresh token from the database.
4. Observe the network requests being made by the application. (you may have to wait 60 for the refreshing of the token)

**Expected behavior**
The client should handle the missing refresh token gracefully and stop attempting to refresh.

**Additional context**
To replicate the issue, artificially shorten the refresh token frequency by configuring the following:
```toml
[auth.session]
[auth.session.accessToken]
expiresIn = 60

[auth.session.refreshToken]
expiresIn = 180
```
