### ISSUE TITLE
allow configuring concealing of errors

### ISSUE THREAD

**Issue by dbarrosop** [nhost/nhost#2839]
```[tasklist]
### Tasks
- [x] backend
- [ ] https://github.com/nhost/nhost/issues/2856
- [x] cli
```

**Comment by dbarrosop** [comment]
this is now configurable, just add the following to your config (no dashboard support yet but you can use the editor in the dashboard):

```toml
[auth.misc]
concealErrors = true
```
