### ISSUE TITLE
[Auth] disableNewUsers not taken into account when signUp with a social provider

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#2914]
**To Reproduce**
1. Use the following configuration
```toml
[auth.signUp]
enabled = true
disableNewUsers = true
```

3. Try to signUp using a social provider
4. The user is created but not disabled

You can test on cjowxjndebxkxerzhmtd

**Expected behavior**
Using a social provider or not, if the toml ask to disableNewUsers, then new users must be disabled

**Screenshots**
![image](https://github.com/user-attachments/assets/eea9c556-aa33-443e-b741-b44986bd126b)
