### ISSUE TITLE
server_url not fully supported in confirmation link

### ISSUE THREAD

**Issue by sangdth** [nhost/nhost#331]
I have an react native app and need to test on real device, since the localhost is not work on real devices, ngrok is the rescue.

@elitan [suggested me](https://discord.com/channels/552499021260914688/958403936723816500) to change the `server_url` in config.yaml and it changes the confirmation link, but when I click on it, I got error.

https://github.com/sangdth/custom-backend-url-issue

#### 1. Get ngrok up and running with these map:

```
# make sure to change your sub domains
tunnels:
  frontend:
    proto: http
    addr: 3000
    subdomain: yourfrontend
  backend:
    proto: http
    addr: 1337
    subdomain: yourbackend

# then run
ngrok start --all
```
#### 2. Get nhost up and running with these changes in `config.yaml`:
- Change the `server_url` to `https://yourbackend.ngrok.io`
- Change the `client_url` to `https://yourfrontend.ngrok.io`

After signup, open mailhog and you will see the confirmation should look like:
```
http://yourbackend.ngrok.io/verify?&ticket=verifyEmail:xxxxxxxxxxxxxx&type=emailVerify&redirectTo=http://yourfrontend.ngrok.io/
```

#### 3a. ~~Click on the link and the error will occur.~~ Happened on `http`
```
Access to fetch at 'http://localhost:9208/v1/metadata' from origin 'http://yourbackend.ngrok.io'
has been blocked by CORS policy: The request client is not a secure context and the resource is 
in more-private address space `local`.
```
- The user email is not confirmed.

#### 3b: After changing to `https`, the CORS issue is gone, but new error come with 404

<img width="1232" alt="Screenshot 2022-04-12 at 13 13 54" src="https://user-images.githubusercontent.com/1083478/162938466-cfb07137-a7c3-4458-bb94-5cdb80a324f4.png">

## Expected:
The confirmation link will work and redirect user to http://yourfrontend.ngrok.io

**Comment by jladuval** [comment]
Would be awesome to hear what the suggested workaround for this is. Local development is a little tricky right now.

**Comment by plmercereau** [comment]
Please add `/v1/auth` to the auth `server_url` settings in your Nhost `config.yaml`:
```yaml
auth:
  client_url: https://yourfrontend.ngrok.io
  server_url: https://yourbackend.ngrok.io/v1/auth
```
