### ISSUE TITLE
Redirect error with social login after signing in on local

### ISSUE THREAD

**Issue by alveshelio** [nhost/nhost#478]
I've set up LinkedIn login in local. I've added this to my `nhost/config.yaml` file
```yaml
auth:
  ...
  server_url: http://localhost:1337/v1/auth
  client_url: http://localhost:3000
  ...
   linkedin:
      client_id: "my_client_id"
      client_secret: "my_client_secret"
      enabled: true
      scope: r_emailaddress,r_liteprofile
```

And this is the redirect URL set in the LinkedIn app: http://localhost:1337/v1/auth/signin/provider/linkedin/callback

And I'm using this to sign in:
```ts
const login = async (provider: Provider): Promise<void> => {
    await auth.signIn({
      provider: 'linkedin',
    })
  }
```

I'm able to login, however when it redirects back, it redirects to http://localhost:1337/v1/auth/signin/provider/linkedin/undefined#refreshToken=7573ca41-603a-4ca6-a48b-5e2cf69734aa

If I remove the `/undefined` it works fine. I'm not sure if I'm missing something in the configuration of this is a bug.
