### ISSUE TITLE
Default docker-compose.yaml does not respond when signing up

### ISSUE THREAD

**Issue by heygambo** [nhost/nhost#499]
Hey,

I'm trying out nhost locally using the docker-compose file in this repo:
I've run `docker-compose pull` to make sure I have all the latest images

`docker-compose.yaml` for reference:
```yaml
version: '3.6'
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1337"
    ports:
      - "1337:1337"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.2.0
    depends_on:
      - 'postgres'
    restart: unless-stopped
    expose:
      - 8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.hasura.entrypoints=web"
  auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - postgres
      - graphql-engine
    restart: unless-stopped
    environment:
      AUTH_HOST: '0.0.0.0'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      AUTH_CLIENT_URL: ${AUTH_CLIENT_URL:-http://localhost:3000}
      AUTH_SMTP_HOST: mailhog
      AUTH_SMTP_PORT: 1025
      AUTH_EMAIL_PASSWORDLESS_ENABLED: true
    expose:
      - 4000
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=/v1/auth"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/v1/auth`)"
      - "traefik.http.routers.auth.middlewares=strip-auth@docker"
      - "traefik.http.routers.auth.entrypoints=web"
  storage:
    image: nhost/hasura-storage:0.1.5
    depends_on:
      - postgres
      - graphql-engine
      - minio
    restart: unless-stopped
    expose:
      - 8000
    healthcheck:
      disable: true
    environment:
      PUBLIC_URL: http://localhost:${PROXY_PORT:-1337}
      HASURA_METADATA: 1
      HASURA_ENDPOINT: http://graphql-engine:8080/v1
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      S3_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      S3_SECRET_KEY: ${STORAGE_SECRET_KEY}
      S3_ENDPOINT: http://minio:8484
      S3_BUCKET: liveslide-gambo-dev
      POSTGRES_MIGRATIONS: 1
      POSTGRES_MIGRATIONS_SOURCE: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres?sslmode=disable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage.rule=Host(`localhost`) && PathPrefix(`/v1/storage`)"
      - "traefik.http.routers.storage.entrypoints=web"
    command: serve
  minio:
    image: minio/minio:RELEASE.2021-09-24T00-24-24Z
    entrypoint: sh
    command: -c 'mkdir -p /data/nhost && /opt/bin/minio server --address :8484 /data'
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    ports:
      - ${MINIO_PORT:-8484}:8484
    volumes:
      - ./data/minio:/data
  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      SMTP_USER: ${AUTH_SMTP_USER:-user}
      SMTP_SECURE: "${AUTH_SMTP_SECURE:-false}"
      SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    ports:
      - ${AUTH_SMTP_PORT:-1025}:1025
      - 8025:8025
    volumes:
      - ./data/mailhog:/maildir
```

The front-end code:
```vue
<script setup>
import { ref } from 'vue'
import { NhostClient } from '@nhost/nhost-js'

const nhost = new NhostClient({
  backendUrl: 'http://localhost:1337'
})

const email = ref('hey@example.com')
const password = ref('hey@example.com')

async function onSignUp (event) {
  const payload = {
    email: email.value,
    password: password.value
  }
  console.log("🚀 ~ file: sign-up.vue ~ line 46 ~ onSignUp ~ payload", payload)
  const { session, error } = await nhost.auth.signUp(payload)
  console.log("🚀 ~ file: sign-up.vue ~ line 44 ~ onSignUp ~ error", error)
  console.log("🚀 ~ file: sign-up.vue ~ line 47 ~ onSignUp ~ session", session)
}
</script>
```

The server is responding with an error 500. The browser does not receive a session.

server log from `nhost-auth-1`
```
{
  "level": 30,
  "time": 1651567947404,
  "pid": 19,
  "hostname": "a1b9abfaa12e",
  "req": {
    "id": 2,
    "method": "POST",
    "url": "/signup/email-password",
    "query": {},
    "params": {},
    "headers": {
      "host": "localhost:1337",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
      "content-length": "50",
      "accept": "application/json, text/plain, */*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,id;q=0.6",
      "cache-control": "no-cache",
      "content-type": "application/json",
      "dnt": "1",
      "origin": "http://localhost:3000",
      "pragma": "no-cache",
      "referer": "http://localhost:3000/",
      "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": "\"macOS\"",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "x-forwarded-for": "172.27.0.1",
      "x-forwarded-host": "localhost:1337",
      "x-forwarded-port": "1337",
      "x-forwarded-prefix": "/v1/auth",
      "x-forwarded-proto": "http",
      "x-forwarded-server": "e2abc27339af",
      "x-real-ip": "172.27.0.1"
    },
    "remoteAddress": "::ffff:172.27.0.3",
    "remotePort": 40242
  },
  "res": {
    "statusCode": 500,
    "headers": {
      "x-dns-prefetch-control": "off",
      "x-frame-options": "SAMEORIGIN",
      "strict-transport-security": "max-age=15552000; includeSubDomains",
      "x-download-options": "noopen",
      "x-content-type-options": "nosniff",
      "x-xss-protection": "1; mode=block",
      "access-control-allow-origin": "*",
      "surrogate-control": "no-store",
      "cache-control": "no-store, no-cache, must-revalidate, proxy-revalidate",
      "pragma": "no-cache",
      "expires": "0"
    }
  },
  "err": {
    "type": "Error",
    "message": "failed with status code 500",
    "stack": "Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/node_modules/.pnpm/pino-http@5.8.0/node_modules/pino-http/logger.js:77:38)\n    at ServerResponse.emit (events.js:412:35)\n    at onFinish (_http_outgoing.js:792:10)\n    at afterWrite (internal/streams/writable.js:466:5)\n    at afterWriteTick (internal/streams/writable.js:453:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
  },
  "responseTime": 341,
  "msg": "request errored"
}
```

Not sure if this is helpful information but here are my docker desktop versions:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/449438/166428221-ca1c5300-2836-4310-8706-c64d56943cdb.png">

Update:
I've noticed this log line in auth before the error:
```
{"level":50,"time":1651571318721,"pid":19,"hostname":"3df9602d9e51","msg":"Missing credentials for \"PLAIN\""}
```

Could this error have to do with the auth service not being able to connect to mailhog?
