### ISSUE TITLE
auth: token: access: expires_in: is not respected in config.yaml

### ISSUE THREAD

**Issue by kratam** [nhost/nhost#565]
No matter what I set in `config.yaml` for access token expiration, the default 900 is used.

Here's the `config.yaml`:
```yaml
auth:
  #...
  token:
    access:
      expires_in: 30
```

**Comment by plmercereau** [comment]
hello,
could you try
```yaml
auth:
  access_token:
    expires_in: 30
```

**Comment by kratam** [comment]
It works, thanks.

**Comment by mrkpatchaa** [comment]
@kratam @plmercereau I couldn't get it work on my side. Still having the default 900.
Also, the structure that comes with nhost init is 
```yaml
auth:
  token:
    access:
      expires_in: 900
    refresh:
      expires_in: 43200
```
but you're suggesting to use 
```yaml
auth:
  access_token:
    expires_in: 30
```
In my case I want longer sessions so I made this change
```yaml
auth:
  access_token:
    expires_in: 86400
```
And it's not working.
