### ISSUE TITLE
Format for Twilio SMS provider is incorrect when creating config from CLI

### ISSUE THREAD

**Issue by franzwilhelm** [nhost/nhost#782]
The config reference is on this form

```yaml
  sms:
    enabled: true
    passwordless:
      enabled: true
    provider:
      twilio:
        account_sid: ""
        auth_token: ""
        from: ""
        messaging_service_id: ""
```

But as stated out in [this issue](https://github.com/nhost/nhost/issues/467), the correct reference looks like this:

```yaml
  sms:
    enabled: true
    passwordless:
      enabled: true
    provider: 'twilio'
    twilio:
      account_sid: ""
      auth_token: ""
      from: ""
      messaging_service_id: ""
```

In general there is no schema definition for the config.yaml, so it's impossible to know what the correct structure looks like. Don't close this issue before that is resolved and communicated in the docs
