### ISSUE TITLE
Add Hasura environment variables to make entire schema camelCase

### ISSUE THREAD

**Issue by joserocha3** [nhost/nhost#793]
Product is awesome so far, excited to get an app into production!

I am wondering if it's possible to set some Hasura environment variables to be able to use [camel case naming convention](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/naming-convention/#introduction). I can set them in `nhost/config.yml` for local development, but not via the Nhost console. 

It would be great if we could get those variables available in Nhost cloud console, or maybe I am overlooking how to do it?

**Cannot set in console:**

<img width="350" alt="Screen Shot 2022-07-04 at 10 11 47 PM" src="https://user-images.githubusercontent.com/11415340/177242127-ee6b17ff-b13e-4028-8b24-df70396d138c.png">

**This works locally:**

```yml
metadata_directory: metadata
services:
  hasura:
    version: v2.8.3
    environment:
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
```

I can set a graphQL name via the Hasura console, but that only changes the field names, not the entire schema.

**Comparison:**

<img width="500" alt="Screen Shot 2022-07-04 at 10 23 40 PM" src="https://user-images.githubusercontent.com/11415340/177243767-8b733f0f-a6a2-4da0-8e5c-b8e9aa31e08d.png">
